export const NAVIGATION_NAME = {
  AUTH: {
    welcomeScreen: 'WelcomeScreen',
    loginScreen: 'LoginScreen',
    registerStep1Screen: 'RegisterStep1Screen',
    registerStep2Screen: 'RegisterStep2Screen',
    registerStep3Screen: 'RegisterStep3Screen',
    registerStep4Screen: 'RegisterStep4Screen',
    registerStep5Screen: 'RegisterStep5Screen',
    registerStep6Screen: 'RegisterStep6Screen',
    registerSuccessScreen: 'RegisterSuccessScreen',
    customTargetScreen: 'CustomTargetScreen',
  },
  MAIN: {
    homeScreen: 'HomeScreen',
    goalDetailScreen: 'GoalDetailScreen',
    scanScreen: 'ScanScreen',
    scanDetailScreen: 'ScanDetailScreen',
    journalScreen: 'JournalScreen',
    journalDetailScreen: 'JournalDetailScreen',
    statisticScreen: 'StatisticScreen',
    profileScreen: 'ProfileScreen',
    profileChangeAboutScreen: 'ProfileChangeAboutScreen',
    profileChangePasswordScreen: 'ProfileChangePasswordScreen',
  },
};
